version: '2'
services:
    elasticsearch:
        image: elasticsearch:5.2.1
        network_mode: host
        ports: 
            - 9200:9200
            - 9300:9300
        volumes:
            - ./data:/usr/share/elasticsearch/data
            - ./plugins:/usr/share/elasticsearch/plugins
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
